/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 Attacking.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Attacking.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="KID_NINJA_KATANA">
            <skinnedMesh name="KID_NINJA_KATANA001" geometry={nodes.KID_NINJA_KATANA001.geometry} material={materials['map_KidNinja1.003']} skeleton={nodes.KID_NINJA_KATANA001.skeleton} />
            <skinnedMesh name="KID_NINJA_KATANA001_1" geometry={nodes.KID_NINJA_KATANA001_1.geometry} material={materials['Material.005']} skeleton={nodes.KID_NINJA_KATANA001_1.skeleton} />
            <skinnedMesh name="KID_NINJA_KATANA001_2" geometry={nodes.KID_NINJA_KATANA001_2.geometry} material={materials['map_KidNinja1.004']} skeleton={nodes.KID_NINJA_KATANA001_2.skeleton} />
            <skinnedMesh name="KID_NINJA_KATANA001_3" geometry={nodes.KID_NINJA_KATANA001_3.geometry} material={materials['Material.006']} skeleton={nodes.KID_NINJA_KATANA001_3.skeleton} />
            <skinnedMesh name="KID_NINJA_KATANA001_4" geometry={nodes.KID_NINJA_KATANA001_4.geometry} material={materials['Material.007']} skeleton={nodes.KID_NINJA_KATANA001_4.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Attacking.gltf')
