/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 landing.gltf
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/landing.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Spectacles.geometry} material={materials.GLASSES} position={[-0.04, 3.21, 0.39]} scale={1.15} />
      <group position={[0.47, 0.81, 0.29]} rotation={[0, 0.48, 0]} scale={1.15}>
        <mesh geometry={nodes.Cube007.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Cube007_1.geometry} material={materials['Wool.001']} />
        <mesh geometry={nodes.Cube007_2.geometry} material={materials['Material.020']} />
      </group>
      <mesh geometry={nodes.Main_Body.geometry} material={materials['Black Base.001']} position={[-0.04, 3.37, 0.09]} scale={1.15} />
      <group position={[-0.05, 2.24, 0.34]} scale={1.15}>
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002.geometry} material={materials.Default_OBJ} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_1.geometry} material={materials['Default_OBJ.002']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_2.geometry} material={materials['Default_OBJ.001']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_3.geometry} material={materials['SVGMat.001']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_4.geometry} material={materials['SVGMat.033']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_5.geometry} material={materials['SVGMat.065']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_6.geometry} material={materials['SVGMat.070']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_7.geometry} material={materials['SVGMat.078']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_8.geometry} material={materials['SVGMat.083']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_9.geometry} material={materials['SVGMat.109']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_10.geometry} material={materials['SVGMat.110']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_11.geometry} material={materials['SVGMat.111']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_12.geometry} material={materials['SVGMat.112']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_13.geometry} material={materials['SVGMat.113']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_14.geometry} material={materials['SVGMat.114']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_15.geometry} material={materials['SVGMat.115']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_16.geometry} material={materials['SVGMat.116']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_17.geometry} material={materials['SVGMat.117']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_18.geometry} material={materials['SVGMat.118']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_19.geometry} material={materials['SVGMat.119']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_20.geometry} material={materials['SVGMat.120']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_21.geometry} material={materials['SVGMat.121']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_22.geometry} material={materials['SVGMat.122']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_23.geometry} material={materials['SVGMat.123']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_24.geometry} material={materials['SVGMat.124']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_25.geometry} material={materials['SVGMat.125']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_26.geometry} material={materials['SVGMat.126']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_27.geometry} material={materials['SVGMat.127']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_28.geometry} material={materials['SVGMat.128']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_29.geometry} material={materials['SVGMat.129']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_30.geometry} material={materials['SVGMat.130']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_31.geometry} material={materials['SVGMat.131']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_32.geometry} material={materials['SVGMat.132']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_33.geometry} material={materials['SVGMat.133']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_34.geometry} material={materials['SVGMat.134']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_35.geometry} material={materials['SVGMat.135']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_36.geometry} material={materials['SVGMat.136']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_37.geometry} material={materials['SVGMat.137']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_38.geometry} material={materials['SVGMat.138']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_39.geometry} material={materials['SVGMat.139']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_40.geometry} material={materials['SVGMat.140']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_41.geometry} material={materials['SVGMat.141']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_42.geometry} material={materials['SVGMat.142']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_43.geometry} material={materials['SVGMat.143']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_44.geometry} material={materials['SVGMat.144']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_45.geometry} material={materials['SVGMat.145']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_46.geometry} material={materials['SVGMat.146']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_47.geometry} material={materials['SVGMat.147']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_48.geometry} material={materials['SVGMat.148']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_49.geometry} material={materials['SVGMat.149']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_50.geometry} material={materials['SVGMat.150']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_51.geometry} material={materials['SVGMat.151']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_52.geometry} material={materials['SVGMat.152']} />
        <mesh geometry={nodes.nike_tech_Default_OBJ_0002_53.geometry} material={materials['SVGMat.153']} />
      </group>
      <group position={[-0.07, 3.54, 0.29]} rotation={[2.88, -0.04, 3.14]} scale={1.15}>
        <mesh geometry={nodes.Object_33001.geometry} material={materials.Cap_Mat_Black} />
        <mesh geometry={nodes.Object_33001_1.geometry} material={materials['Material399479.002']} />
        <mesh geometry={nodes.Object_33001_2.geometry} material={materials['Material399497.002']} />
        <mesh geometry={nodes.Object_33001_3.geometry} material={materials['Material399606.002']} />
        <mesh geometry={nodes.Object_33001_4.geometry} material={materials['Material399726.002']} />
        <mesh geometry={nodes.Object_33001_5.geometry} material={materials['Material399846.002']} />
        <mesh geometry={nodes.Object_33001_6.geometry} material={materials['FABRIC_2_FRONT_399248.002']} />
        <mesh geometry={nodes.Object_33001_7.geometry} material={materials['Cotton_40s_Chambray_Copy_1_FRONT_399260.002']} />
        <mesh geometry={nodes.Object_33001_8.geometry} material={materials['Cotton_40s_Chambray_Copy_3_FRONT_399274.002']} />
        <mesh geometry={nodes.Object_33001_9.geometry} material={materials['Plastic_FRONT_399255.002']} />
        <mesh geometry={nodes.Object_33001_10.geometry} material={materials['Cotton_40s_Chambray_Copy_2_FRONT_399267.002']} />
        <mesh geometry={nodes.Object_33001_11.geometry} material={materials['SVGMat.254']} />
        <mesh geometry={nodes.Object_33001_12.geometry} material={materials['SVGMat.255']} />
        <mesh geometry={nodes.Object_33001_13.geometry} material={materials['SVGMat.256']} />
        <mesh geometry={nodes.Object_33001_14.geometry} material={materials['SVGMat.257']} />
        <mesh geometry={nodes.Object_33001_15.geometry} material={materials['SVGMat.258']} />
        <mesh geometry={nodes.Object_33001_16.geometry} material={materials['SVGMat.259']} />
        <mesh geometry={nodes.Object_33001_17.geometry} material={materials['SVGMat.260']} />
        <mesh geometry={nodes.Object_33001_18.geometry} material={materials['SVGMat.261']} />
        <mesh geometry={nodes.Object_33001_19.geometry} material={materials['SVGMat.262']} />
        <mesh geometry={nodes.Object_33001_20.geometry} material={materials['SVGMat.263']} />
        <mesh geometry={nodes.Object_33001_21.geometry} material={materials['SVGMat.264']} />
        <mesh geometry={nodes.Object_33001_22.geometry} material={materials['SVGMat.265']} />
        <mesh geometry={nodes.Object_33001_23.geometry} material={materials['SVGMat.266']} />
        <mesh geometry={nodes.Object_33001_24.geometry} material={materials['SVGMat.267']} />
        <mesh geometry={nodes.Object_33001_25.geometry} material={materials['SVGMat.268']} />
        <mesh geometry={nodes.Object_33001_26.geometry} material={materials['SVGMat.269']} />
        <mesh geometry={nodes.Object_33001_27.geometry} material={materials['SVGMat.270']} />
        <mesh geometry={nodes.Object_33001_28.geometry} material={materials['SVGMat.271']} />
        <mesh geometry={nodes.Object_33001_29.geometry} material={materials['SVGMat.272']} />
        <mesh geometry={nodes.Object_33001_30.geometry} material={materials['SVGMat.273']} />
        <mesh geometry={nodes.Object_33001_31.geometry} material={materials['SVGMat.274']} />
        <mesh geometry={nodes.Object_33001_32.geometry} material={materials['SVGMat.275']} />
        <mesh geometry={nodes.Object_33001_33.geometry} material={materials['SVGMat.276']} />
        <mesh geometry={nodes.Object_33001_34.geometry} material={materials['SVGMat.277']} />
        <mesh geometry={nodes.Object_33001_35.geometry} material={materials['SVGMat.278']} />
        <mesh geometry={nodes.Object_33001_36.geometry} material={materials['SVGMat.279']} />
        <mesh geometry={nodes.Object_33001_37.geometry} material={materials['SVGMat.280']} />
        <mesh geometry={nodes.Object_33001_38.geometry} material={materials['SVGMat.281']} />
        <mesh geometry={nodes.Object_33001_39.geometry} material={materials['SVGMat.282']} />
        <mesh geometry={nodes.Object_33001_40.geometry} material={materials['SVGMat.283']} />
        <mesh geometry={nodes.Object_33001_41.geometry} material={materials['SVGMat.284']} />
        <mesh geometry={nodes.Object_33001_42.geometry} material={materials['SVGMat.285']} />
        <mesh geometry={nodes.Object_33001_43.geometry} material={materials['SVGMat.286']} />
        <mesh geometry={nodes.Object_33001_44.geometry} material={materials['SVGMat.287']} />
        <mesh geometry={nodes.Object_33001_45.geometry} material={materials['SVGMat.288']} />
        <mesh geometry={nodes.Object_33001_46.geometry} material={materials['SVGMat.289']} />
        <mesh geometry={nodes.Object_33001_47.geometry} material={materials['SVGMat.290']} />
        <mesh geometry={nodes.Object_33001_48.geometry} material={materials['SVGMat.291']} />
        <mesh geometry={nodes.Object_33001_49.geometry} material={materials['SVGMat.292']} />
        <mesh geometry={nodes.Object_33001_50.geometry} material={materials['SVGMat.293']} />
        <mesh geometry={nodes.Object_33001_51.geometry} material={materials['SVGMat.294']} />
        <mesh geometry={nodes.Object_33001_52.geometry} material={materials['SVGMat.295']} />
        <mesh geometry={nodes.Object_33001_53.geometry} material={materials['SVGMat.296']} />
        <mesh geometry={nodes.Object_33001_54.geometry} material={materials['SVGMat.297']} />
        <mesh geometry={nodes.Object_33001_55.geometry} material={materials['SVGMat.298']} />
        <mesh geometry={nodes.Object_33001_56.geometry} material={materials['SVGMat.299']} />
        <mesh geometry={nodes.Object_33001_57.geometry} material={materials['SVGMat.300']} />
        <mesh geometry={nodes.Object_33001_58.geometry} material={materials['SVGMat.301']} />
        <mesh geometry={nodes.Object_33001_59.geometry} material={materials['SVGMat.302']} />
        <mesh geometry={nodes.Object_33001_60.geometry} material={materials['SVGMat.303']} />
        <mesh geometry={nodes.Object_33001_61.geometry} material={materials['SVGMat.304']} />
      </group>
      <group position={[-1.58, 0.61, 0.09]} rotation={[0, -1.57, 0]} scale={1.15}>
        <mesh geometry={nodes.mesh001.geometry} material={materials['Hard Rough Plastic Black #1']} />
        <mesh geometry={nodes.mesh001_1.geometry} material={materials['Steel Rough #1']} />
        <mesh geometry={nodes.mesh001_2.geometry} material={materials['Hard Rough Plastic Black']} />
        <mesh geometry={nodes.mesh001_3.geometry} material={materials['Steel Rough #2']} />
        <mesh geometry={nodes.mesh001_4.geometry} material={materials['Steel Rough #2.001']} />
        <mesh geometry={nodes.mesh001_5.geometry} material={materials['Steel Rough']} />
        <mesh geometry={nodes.mesh001_6.geometry} material={materials['Steel Rough.001']} />
        <mesh geometry={nodes.mesh001_7.geometry} material={materials['Steel Rough.002']} />
        <mesh geometry={nodes.mesh001_8.geometry} material={materials['Steel Rough.003']} />
        <mesh geometry={nodes.mesh001_9.geometry} material={materials['Hard Rough Plastic Black #2']} />
        <mesh geometry={nodes.mesh001_10.geometry} material={materials['Brass Rough']} />
        <mesh geometry={nodes.mesh001_11.geometry} material={materials['Brass Rough.001']} />
        <mesh geometry={nodes.mesh001_12.geometry} material={materials['Brass Rough.002']} />
        <mesh geometry={nodes.mesh001_13.geometry} material={materials['Brass Rough.003']} />
        <mesh geometry={nodes.mesh001_14.geometry} material={materials['Brass Rough.004']} />
        <mesh geometry={nodes.mesh001_15.geometry} material={materials['Brass Rough.005']} />
        <mesh geometry={nodes.mesh001_16.geometry} material={materials['Brass Rough.006']} />
        <mesh geometry={nodes.mesh001_17.geometry} material={materials['Brass Rough.007']} />
        <mesh geometry={nodes.mesh001_18.geometry} material={materials['Brass Rough.008']} />
        <mesh geometry={nodes.mesh001_19.geometry} material={materials['Steel Rough.004']} />
        <mesh geometry={nodes.mesh001_20.geometry} material={materials['Steel Rough.005']} />
        <mesh geometry={nodes.mesh001_21.geometry} material={materials['Steel Rough.006']} />
        <mesh geometry={nodes.mesh001_22.geometry} material={materials['Steel Rough.007']} />
        <mesh geometry={nodes.mesh001_23.geometry} material={materials['Steel Rough #3']} />
        <mesh geometry={nodes.mesh001_24.geometry} material={materials['Steel Rough #3.001']} />
        <mesh geometry={nodes.mesh001_25.geometry} material={materials['Steel Rough #3.002']} />
        <mesh geometry={nodes.mesh001_26.geometry} material={materials['Steel Rough #3.003']} />
        <mesh geometry={nodes.mesh001_27.geometry} material={materials['Steel Rough #3.004']} />
        <mesh geometry={nodes.mesh001_28.geometry} material={materials['Steel Rough #3.005']} />
        <mesh geometry={nodes.mesh001_29.geometry} material={materials['Steel Rough #1.001']} />
        <mesh geometry={nodes.mesh001_30.geometry} material={materials['Steel Rough #1.002']} />
        <mesh geometry={nodes.mesh001_31.geometry} material={materials['Steel Rough #1.003']} />
        <mesh geometry={nodes.mesh001_32.geometry} material={materials['Steel Rough #1.004']} />
        <mesh geometry={nodes.mesh001_33.geometry} material={materials['Steel Rough #1.005']} />
        <mesh geometry={nodes.mesh001_34.geometry} material={materials['Steel Rough #5']} />
        <mesh geometry={nodes.mesh001_35.geometry} material={materials['Steel Rough #5.001']} />
        <mesh geometry={nodes.mesh001_36.geometry} material={materials['Steel Rough #5.002']} />
        <mesh geometry={nodes.mesh001_37.geometry} material={materials['Steel Rough #4.001']} />
      </group>
      <mesh geometry={nodes.Beak.geometry} material={materials['Material.001']} position={[-0.04, 3.32, 0.8]} scale={1.15} />
      <group position={[0.17, 3.65, 0.53]} rotation={[Math.PI / 2, 0, 0]} scale={1.15}>
        <mesh geometry={nodes.Eyes.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Eyes_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Eyes_2.geometry} material={materials['Material.004']} />
      </group>
      <mesh geometry={nodes.Circle005.geometry} material={materials['Pointiness Metal.004']} position={[-0.04, 0.1, 0.09]} scale={1.15} />
      <mesh geometry={nodes.Circle002.geometry} material={materials['Pointiness Metal.001']} position={[-0.04, 0.05, 0.09]} scale={1.15} />
      <mesh geometry={nodes.Circle.geometry} material={materials['Pointiness Metal.001']} position={[-0.04, 0.05, 0.09]} scale={1.15} />
    </group>
  )
}

useGLTF.preload('/landing.gltf')
