/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 p1.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/p1.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Hot_Sauce">
          <mesh name="Hot_Sauce_1" geometry={nodes.Hot_Sauce_1.geometry} material={materials.Artics} />
          <mesh name="Hot_Sauce_2" geometry={nodes.Hot_Sauce_2.geometry} material={materials['Material.001']} />
          <mesh name="Hot_Sauce_3" geometry={nodes.Hot_Sauce_3.geometry} material={materials['Material.002']} />
          <mesh name="Hot_Sauce_4" geometry={nodes.Hot_Sauce_4.geometry} material={materials['Material.003']} />
          <mesh name="Hot_Sauce_5" geometry={nodes.Hot_Sauce_5.geometry} material={materials['Material.004']} />
          <mesh name="Hot_Sauce_6" geometry={nodes.Hot_Sauce_6.geometry} material={materials['artic blue']} />
          <mesh name="Hot_Sauce_7" geometry={nodes.Hot_Sauce_7.geometry} material={materials['Material.018']} />
          <mesh name="Hot_Sauce_8" geometry={nodes.Hot_Sauce_8.geometry} material={materials['Material.019']} />
          <mesh name="Hot_Sauce_9" geometry={nodes.Hot_Sauce_9.geometry} material={materials['Material.020']} />
          <mesh name="Hot_Sauce_10" geometry={nodes.Hot_Sauce_10.geometry} material={materials['Material.017']} />
          <mesh name="Hot_Sauce_11" geometry={nodes.Hot_Sauce_11.geometry} material={materials.Logo} />
          <mesh name="Hot_Sauce_12" geometry={nodes.Hot_Sauce_12.geometry} material={materials.Base2} />
          <mesh name="Hot_Sauce_13" geometry={nodes.Hot_Sauce_13.geometry} material={materials.lambert1} />
          <mesh name="Hot_Sauce_14" geometry={nodes.Hot_Sauce_14.geometry} material={materials.Cordones} />
          <mesh name="Hot_Sauce_15" geometry={nodes.Hot_Sauce_15.geometry} material={materials.Suela} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/p1.gltf')
