/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 p2.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/p2.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Retopo_Sphere" position={[0, 0.06, -0.01]} scale={0.18}>
          <mesh name="mesh001" geometry={nodes.mesh001.geometry} material={materials['artic blue.001']} />
          <mesh name="mesh001_1" geometry={nodes.mesh001_1.geometry} material={materials['Material.005']} />
          <mesh name="mesh001_2" geometry={nodes.mesh001_2.geometry} material={materials['Material.006']} />
          <mesh name="mesh001_3" geometry={nodes.mesh001_3.geometry} material={materials['eye yellow']} />
          <mesh name="mesh001_4" geometry={nodes.mesh001_4.geometry} material={materials['eye red']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/p2.gltf')
