/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 p3.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/p3.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Retopo_Sphere001" position={[0, 0.06, -0.01]} scale={0.19}>
          <mesh name="mesh002" geometry={nodes.mesh002.geometry} material={materials['artic blue.001']} />
          <mesh name="mesh002_1" geometry={nodes.mesh002_1.geometry} material={materials['Material.005']} />
          <mesh name="mesh002_2" geometry={nodes.mesh002_2.geometry} material={materials['Material.006']} />
          <mesh name="mesh002_3" geometry={nodes.mesh002_3.geometry} material={materials['eye yellow']} />
          <mesh name="mesh002_4" geometry={nodes.mesh002_4.geometry} material={materials['eye red']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/p3.gltf')
